import streamlit as st

st.title("SimKO Documentation 👓")

st.markdown("""

## Overview

This tool is an interactive Streamlit application for exploring the downstream molecular effects of simulated protein knockouts (KO). By selecting one or more proteins of interest, the tool partitions cancer cell line cohorts based on natural biological variation—identifying models with low versus median baseline metrics—and tests which downstream molecules change significantly between those groups. 

SimKO integrates mass-spectrometry-based proteomics data alongside matched multi-omic datasets to provide a high-throughput proxy for the systemic consequences of depleting or mutating a given target.

---

## Multi-Omic Core Architecture

**SimKO** combines quantitative deep-proteomics matrices with tightly matched transcriptomic and genomic datasets spanning the same cellular backgrounds.

### Data Sources & Citations

The baseline molecular environments mapped across this platform are compiled from three landmark research efforts:

**Mass Spectrometry Proteomics (The Input Layer):**
   > Nusinow, D. P., Szpyt, J., Ghandi, M., Rose, C. M., McDonald, E. R., 3rd, Kalocsay, M., Jané-Valbuena, J., Gelfand, E., Schweppe, D. K., Jedrychowski, M., Golji, J., Porter, D. A., Rejtar, T., Wang, Y. K., Kryukov, G. V., Stegmeier, F., Erickson, B. K., Garraway, L. A., Sellers, W. R., & Gygi, S. P. (2020). Quantitative Proteomics of the Cancer Cell Line Encyclopedia. *Cell*, *180*(2), 387–402.e16. https://doi.org/10.1016/j.cell.2019.12.023

**Next-Generation Sequencing Transcriptomics and Genomics (The Baseline Layer):**
   > Ghandi, M., Huang, F. W., Jané-Valbuena, J., Kryukov, G. V., Gopal, S., Deik, A., Souza, A., Pierce, K., Keskula, P., Hernandez, D., Ann, J., Shkoza, D., Apfel, V., Zou, Y., Vazquez, F., Barretina, J., Pagliarini, R. A., Galli, G. G., Root, David E., Hahn, William C., Tsherniak, A., Giannakis, M., Schreiber, S. L., Clish, C. B., & Garraway, L. A. (2019). Next-generation characterization of the Cancer Cell Line Encyclopedia. *Nature*, *569*(7757), 503–508. https://doi.org/10.1038/s41586-019-1186-3

**Foundational Cancer Cell Line Encyclopedia Framework:**
   > Barretina, J., Caponigro, G., Stransky, N., Venkatesan, K., Margolin, A. A., Kim, S., Wilson, C. J., Lehár, J., Kryukov, G. V., Sonkin, D., Reddy, A., Liu, M., Murray, L., Berger, M. F., Monahan, J. E., Morais, P., Meltzer, J., Korejwa, A., Jané-Valbuena, J., Mapa, F. A., Thibault, J., Bric-Furlong, E., Raman, P., Shipway, A., & Engels, I. H. (2012). The Cancer Cell Line Encyclopedia enables predictive modelling of anticancer drug sensitivity. *Nature*, *483*(7391), 603–607. https://doi.org/10.1038/nature11003

---

### Experimental Design & Metrics

#### Quantitative Mass Spectrometry Proteomics Matrix
Protein abundance is resolved utilizing high-resolution **Tandem Mass Tag (TMT) 10-plex multiplex mass spectrometry** (Nusinow et al., 2020).
- **Throughput:** Comprises 42 multiplex experiments running 504 individual mass spectrometer allocations mapping **375 human cancer cell line models** derived from 22 distinct tissue frameworks. On average, over 9,000 proteins were quantified per experiment.
- **Quantification Metric:** Quantities are supplied as **$\log_2$-transformed, normalized relative intensities**. Positive values signify relative enrichment over the multiplex master reference channel pool, whereas negative values point to relative depletion against the baseline reference channel used to normalize between runs.

#### Transcriptomic Sequencing Matrix (RNA Expression)
Baseline steady-state transcriptional abundance tracks are established via bulk RNA-Sequencing generated by the Broad Institute CCLE platform (Barretina et al., 2012; Ghandi et al., 2019).
- **Quantification Metric:** Expressed as **$\log_2(\text{TPM} + 1)$** (Transcripts Per Million, with a standard absolute pseudo-count offset of 1 to handle undefined zero values during log transformation).

#### Somatic Variant Coding Selection (Mutation Calls)
The functional presence or absence of mutational variants across coding domains is mapped utilizing Whole Exome Sequencing (WES), Whole Genome Sequencing (WGS), and verified RNA-Seq pipelines (Ghandi et al., 2019).
- **Quantification Metric:** Values are isolated as **binary mutation metrics** ($0 = \text{Wild-Type / Inactive}$, $1 = \text{Mutated / Somatic variant verified}$). Germline artifacts and highly frequent public polymorphisms have been filtered out using common reference repositories (gnomAD/ExAC).

---

### Data Pre-processing & Matrix Alignment

Before integration within the **SimKO** engine, raw data frames underwent structural filtering steps to maintain statistical integrity:

** Sparse Protein Filtering:** Any proteomic feature demonstrating unassigned values across more than 50% of the aggregate cell lines was completely dropped. This avoids unreliable group statistics for proteins detected in only a minority of the panel.
** Conservative Cross-Line Imputation:** Missing values in rows passing the 50% detection threshold were imputed using the **global mean value of that protein across all cell lines**. This aligns missing data with the center of the vector, compressing structural noise and minimizing their influence on differential analysis while avoiding data loss.
** Cohort Co-indexing:** All loaded matrices were co-indexed along identical cell line designators, matching tissue metadata origins. Because imputation and filtering occur prior to loading, all calculation streams operate on a standardized multi-omic data frame at runtime with full coverage across cell lines.

---

### Analytical Data Assumptions

- **Normal Approximations:** Proteomic log-intensities and RNA expression logs are evaluated as continuous, approximately normally distributed datasets. This assumption is justified by the log2-transformed, pre-adjusted normalizations established in the primary literature (Ghandi et al., 2019; Nusinow et al., 2020).
- **Summed Genotypic Counts:** Somatic mutation indices are analyzed via absolute summary counts ($\sum$) within targeted cohorts rather than averages, reflecting a simple binary model burden.
- **RNA–Protein Disconnect:** RNA–protein correlation averages $\sim$0.5 across the proteome, meaning the proteomic layer captures substantial post-transcriptional regulation not visible in raw transcript data.

---

## Suitability of the Data for This Tool

The integrated dataset is exceptionally well-suited to the type of analysis this tool performs, with some important caveats worth noting.

**Breadth of coverage.** With 375 cell lines across 22 tissue types and $\sim$9,000+ proteins per experiment, there is sufficient statistical power to meaningfully compare groups of 20 cell lines and detect differential molecular changes.

**Natural variation as a proxy for depletion.** The tool leverages the fact that molecular abundance varies naturally across cell lines due to differences in gene expression, copy number, mutation, and post-transcriptional regulation. Cell lines at the low end of abundance for a given protein serve as a natural model for its partial depletion, which is a widely used approach in correlative analysis.

---

## Methodological Pipeline

### Step 1 — Cohort Partitioning and Classification

For a selected protein target, the tool sorts cell lines (optionally restricted by tissue type) and partitions them into distinct analytical classes based on the chosen multi-omic view:

| Tab / Analysis View | Target Basis | Cohort 1 Group | Cohort 2 Group |
|---|---|---|---|
| **Abundance Effects** | Proteomics Mean | **Low Abundance:** Bottom $n$ cell lines | **Median Abundance:** Middle $n$ baseline lines |
| **Expression Effects** | $\log_2(\text{TPM}+1)$ Mean | **Low Expression:** Bottom $n$ cell lines | **Median Expression:** Middle $n$ baseline lines |
| **Mutation Effects** | Somatic Alteration | **Mutated:** $\ge 1$ non-synonymous variant | **Non-Mutated:** Wild-Type (WT) copies |

#### Determining Class Size ($n$):
For continuous distributions (Abundance and Expression views), the cohort size ($n$) scales dynamically based on sample size to maximize statistical constraints:
- If fewer than 60 total cell lines match the selected tissue filters: $n = (\text{total\_cell\_lines} - 1) // 3$
- If 60 or more cell lines are available in the panel: $n = 20$

Using the **median group as the reference baseline** is an intentional architectural choice. It avoids the confounding effects of "high vs low" extreme comparisons, which frequently pick up generalized stress or hyper-proliferation phenotypes rather than specific target biology. The median group acts as a standard biological baseline.

### Step 2 — Differential Statistical Calculations

For each data type, the platform compares molecular behavior between the partitioned groups:

#### Continuous Features (Abundance and Expression Matrices)
Group means and standard deviations are computed across all background features. An independent **two-sample Student's t-test** (assuming pooled variance, two-tailed) is performed using the formula:

$$t = \frac{\bar{X}_1 - \bar{X}_2}{s_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}$$

Where $s_p$ represents the pooled standard deviation across both comparative sample frames:

$$s_p = \sqrt{\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}}$$

The resulting $p$-value determines whether a downstream feature's metric varies significantly between the partitioned cohorts. Features showing $p < 0.01$ (or $p < 0.05$ on the Mutation layout) are prioritized as significantly altered tracking candidates.

#### Binary Features (Mutation Matrix)
Somatic variant counts are aggregated as raw absolute sums inside each comparative cohort. The reported differential is calculated as:

$$\Delta_{\text{Mutation}} = \sum \text{Mutated Cohort} - \sum \text{Non-Mutated Cohort}$$

No significance testing is applied directly to mutation counts.

---

## Using the Tool

### Global Settings
Configure parameters globally on the **Global Settings** tab. Use the multi-select inputs to determine your simulation target (**Proteins for KO**), restrict tracking to specific lineages (**Tissue Filter / Cell Line Filter**), and populate down-stream inspection features (**Selected Protein List**). The Quick Paste panel allows you to paste newline or comma-separated lists directly into the state.

### Multi-Omic Filtering
The **Filter Data** page acts as a structured matrix inspector for the items you specified in your focus tracking lists, breaking down relative values instantly across Abundance, Expression, and Mutation tabs.

### Visualizing Effects
Navigate through the **Abundance**, **Expression**, or **Mutation** effect pages to look at global outputs. The app renders a clustering heatmap representing target groupings, a cumulative multi-gene boxplot, a comprehensive downstream multi-omic differential table, and dynamic outlier tracking sliders.

### Downloading Results
Data exports are directly accessible via the download buttons embedded across individual application tabs:
- **Download All Abundance Foldchange:** Pulls down the completed differential results, tracking values, fold changes, and $p$-values.
- **Download All Abundance:** Pulls down the raw abundance matrix filtered specifically to the active classified cell line cohorts.

---

## Important Caveats & Limitations

1. **Correlation vs Causality:** This application leverages natural baseline variation as a correlative proxy for depletion. Cell lines have not been experimentally manipulated; their low protein or expression values reflect complex, un-engineered cancer biology, including co-occurring copy number alterations, structural passenger events, and long-term adaptation lines.
2. **Lineage Confounding:** Tissue type is a dominant driver of molecular variation. Proteomic and transcriptomic profiles split dramatically between haematopoietic/lymphoid lineages and solid organ backgrounds. Utilizing the built-in **Tissue Filter** is strongly recommended when dealing with lineage-specific pathways to avoid artifact signals.
3. **Imputation Compression:** Because missing values in the proteomics matrix were imputed using cross-cell-line means, features that required heavy imputation will exhibit compressed standard deviations. This can modestly inflate $t$-statistics; proteins that were near the 50% missingness threshold deserve additional scrutiny.
4. **Multiple Testing Correction:** No alpha adjustment (e.g., Benjamini-Hochberg FDR) is automatically applied to runtime $p$-values. Given that thousands of features are computed simultaneously, a raw cutoff of $p < 0.01$ will generate false positives. Treat findings as strong, hypothesis-generating candidates.

---

## Core Dependencies

```text
streamlit
pandas
numpy
scipy
matplotlib
seaborn
            
""")